env:
 - ZMQ="git://github.com/zeromq/zeromq2-x.git"
 - ZMQ="git://github.com/zeromq/zeromq3-x.git -b v3.1.0"
 - ZMQ="git://github.com/zeromq/zeromq3-x.git -b v3.2.4"
 - ZMQ="git://github.com/zeromq/zeromq4-x.git -b v4.0.3" SODIUM="git://github.com/jedisct1/libsodium.git -b 0.4.5"
before_install:
 - sudo apt-get install uuid-dev
 - '[ -n "$SODIUM" ] && git clone --depth 1 $SODIUM libsodium'
 - '[ -n "$SODIUM" ] && cd libsodium'
 - '[ -n "$SODIUM" ] && ./autogen.sh'
 - '[ -n "$SODIUM" ] && ./configure'
 - '[ -n "$SODIUM" ] && make'
 - '[ -n "$SODIUM" ] && sudo make install'
 - '[ -n "$SODIUM" ] && cd ..'
 - git clone --depth 1 $ZMQ zmqlib
 - cd zmqlib
 - ./autogen.sh
 - ./configure
 - make
 - sudo make install
 - sudo /sbin/ldconfig
 - cd ..
language: node_js
node_js:
 - "0.8"
 - "0.10"
 - "0.11"
