language: c
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - uuid-dev

os:
  - linux
  - osx

osx_image: xcode7.2

env:
 # libzmq-4.1.5 prerelease for tweetnacl build fixes
 - ZMQ="b539733cee0f47f9bf1a70dc7cb7ff20410d3380" NODE_VERSION="5"
 - ZMQ="b539733cee0f47f9bf1a70dc7cb7ff20410d3380" NODE_VERSION="4"

before_install:
 - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
 - source ~/.nvm/nvm.sh
 - nvm install $NODE_VERSION
 - nvm use $NODE_VERSION
 - node --version
 - npm --version
 - test "$(uname)" = "Darwin"  || export CXX=g++-4.8 CC=gcc-4.8
 - gcc --version
 - mkdir zmq
 - export ZMQ_PREFIX=`pwd`/zmq
 - export CFLAGS=-fPIC
 - export CXXFLAGS=-fPIC
 - export PKG_CONFIG_PATH=$ZMQ_PREFIX/lib/pkgconfig
 - echo $PKG_CONFIG_PATH
 - wget https://github.com/zeromq/zeromq4-1/archive/$ZMQ.tar.gz -O zeromq-$ZMQ.tar.gz
 - tar xzvf zeromq-$ZMQ.tar.gz
 - cd zeromq4-1-$ZMQ
 - ./autogen.sh
 - ./configure --prefix=$ZMQ_PREFIX --with-tweetnacl --with-relaxed --enable-static --disable-shared
 - V=1 make -j
 - make install
 - cd ..

install: env PKG_CONFIG_PATH=$ZMQ_PREFIX/lib/pkgconfig npm install

script: travis_retry npm test
