environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"

platform:
  - x64
  # - x86 # x86 builds aren't working for now

configuration:
  - release

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install --verbose

test_script:
  - node --version
  - npm --version
  - npm test
