environment:
  GITHUB_TOKEN:
    secure: 8CQgwBRBHNwfTcYdno2yTyyHOhRoSyElm2TzWOCpVh4jPA71l8bXQTxjyoSTJQaf
  matrix:
    - nodejs_version: "4"

platform:
  - x64
  - Win32

configuration:
  - release

install:
  - ps: >-
        if($env:platform -eq "Win32") {
          Install-Product node $env:nodejs_version
        }
        else {
          Install-Product node $env:nodejs_version $env:platform
        }
  - npm install

test_script:
  - node --version
  - npm --version
  - appveyor-retry call npm test

deploy_script:
  - IF "%nodejs_version%;%appveyor_repo_tag%"=="4;true" (npm install prebuild -g & prebuild --all -u %GITHUB_TOKEN%)
