environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"

platform:
  - x64
  - Win32
  # - x86 # x86 builds aren't working for now

configuration:
  - release

install:
  - ps: >-
        if($env:platform -eq "Win32") {
          Install-Product node $env:nodejs_version
        }
        else {
          Install-Product node $env:nodejs_version $env:platform
        }
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
