environment:
  GITHUB_TOKEN:
    secure: 8CQgwBRBHNwfTcYdno2yTyyHOhRoSyElm2TzWOCpVh4jPA71l8bXQTxjyoSTJQaf
  matrix:
    - nodejs_version: "4"

platform:
  - x64
  - x86

build: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - appveyor-retry call npm test

deploy_script:
  - IF "%nodejs_version%;%appveyor_repo_tag%"=="4;true" (npm install prebuild -g & prebuild --all -u %GITHUB_TOKEN%)
